config/routes.rb
Rails.application.routes.draw do
  resources :homeworks do
    post :submit
  end
  root to: 'homeworks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/homework.rb
class Homework < ApplicationRecord
  has_many :operations, class_name: 'Operations::Homework'

  def submit
    Operations::HomeworkSubmit.create(homework: self)
  end
end

app/models/operations.rb
module Operations
  def self.table_name_prefix
    'operations_'
  end
end

app/models/operations/homework.rb
module Operations
  class Homework < ApplicationRecord
    belongs_to :homework
  end
end

app/models/operations/homework_submit.rb
class Operations::HomeworkSubmit < Operations::Homework
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  def create
    @homework = Homework.new(homework_params)

    if @homework.save
      redirect_to @homework, notice: 'Homework was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /homeworks/1
  def update
    if @homework.update(homework_params)
      redirect_to @homework, notice: 'Homework was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /homeworks/1
  def destroy
    @homework.destroy
    redirect_to homeworks_url, notice: 'Homework was successfully destroyed.'
  end

  def submit
    @homework = Homework.find(params[:homework_id])
    @homework.submit
    redirect_to homeworks_url, notice: 'Homework was successfully submitted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def homework_params
      params.require(:homework).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/_form.html.erb
<%= form_with(model: homework) do |form| %>
  <% if homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
        <% homework.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.title %></td>
        <td><%= homework.description %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to 'Submit', homework_submit_path(homework), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @homework.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @homework.description %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homeworker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>